{% set name = "pyqlib" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/qlib/archive/v0.6.1.zip
  sha256: ff2cbbf2126aa8d37cd51827ba05d194bc5835b6c7f89ee952f08c27a7bdf4ab

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy >=1.12.0
    - python >=3.6,<3.9
    - pip
  run:
    - python >=3.6,<3.9
    - {{ pin_compatible('numpy') }}
    - pandas>=0.25.1
    - scipy>=1.0.0
    - requests>=2.18.0
    - sacred>=0.7.4
    - pymongo==3.7.2
    - python-socketio==3.1.2
    - redis>=3.0.1
    - python-redis-lock>=3.3.1
    - schedule>=0.6.0
    - cvxpy==1.0.21
    - hyperopt==0.1.1
    - fire>=0.3.1
    - statsmodels
    - xlrd>=1.0.0
    - plotly==4.12.0
    - matplotlib==3.1.3
    - tables>=3.6.1
    - pyyaml>=5.3.1
    - mlflow>=1.12.1
    - tqdm
    - loguru
    - lightgbm
    - tornado
    - joblib>=0.17.0
    - ruamel.yaml>=0.16.12

test:
  imports:
    - pyqlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simplejson/simplejson
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: MIT
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". (optional)
  license_family: MIT
  # It is strongly encouraged to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: LICENSE
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  # The remaining entries in this section are optional, but recommended.
  description: |
    simplejson is a simple, fast, complete, correct and extensible
    JSON <https://json.org> encoder and decoder for Python 2.5+ and
    Python 3.3+. It is pure Python code with no dependencies, but includes
    an optional C extension for a serious speed boost.
  doc_url: https://simplejson.readthedocs.io/
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - BastianZim
